Add upgrade handler check

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - develop
       - athens2-develop
-      - cicd/remove-excessive-uploads
+      - cicd/upgrade-handler-check
     tags:
       - "*"
   pull_request:
@@ -237,6 +237,18 @@ jobs:
         aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ env.AWS_REGION }}
 
+    - name: Check Upgrade Handler Name Matches Tag Name
+      if: startsWith(github.ref, 'refs/tags/v')
+      run: |
+        UPGRADE_HANDLER_NAME=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
+        echo $UPGRADE_HANDLER_NAME
+        if [ ${{ github.ref_name }} != $UPGRADE_HANDLER_NAME ]; then
+          echo "ERROR: The name of this release (${{ github.ref_name }}) does not match the releaseVersion const in app/setup_handlers.go"
+          echo "Did you forget to update the 'releaseVersion' const in app/setup_handlers.go?" 
+          exit 1
+        fi
+        echo "releaseVersion' const in app/setup_handlers.go matches this tagged release - Moving Forward!"
+        
     - name: upload-files-to-s3
       uses: ./.github/actions/upload-to-s3
       with:
