changes to upgrade handler workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,6 @@ on:
     branches:
       - develop
       - athens2-develop
-      - cicd/fix-go-alpine-build
     tags:
       - "*"
   pull_request:
@@ -31,9 +30,8 @@ jobs:
           [
             buildjet-4vcpu-ubuntu-2204-arm,
             buildjet-4vcpu-ubuntu-2204,
-            buildjet-4vcpu-ubuntu-2004
+            buildjet-4vcpu-ubuntu-2004,
           ]
-
     runs-on: ${{matrix.runs-on}}
     timeout-minutes: 30
     steps:
@@ -96,9 +94,9 @@ jobs:
         env:
           CPU_ARCH: ${{ env.CPU_ARCH }}
         run: |
-            OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
-            cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
-            cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
+          OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
+          cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
+          cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
 
       - name: Save Binaries as Artifacts
         uses: actions/upload-artifact@v3
@@ -110,7 +108,7 @@ jobs:
             zetaclientd-ubuntu-*
 
   build-alpine-and-test:
-    runs-on: ["ubuntu-latest"]
+    runs-on: ubuntu-latest
     timeout-minutes: 30
     steps:
       - uses: actions/checkout@v3
@@ -155,6 +153,16 @@ jobs:
         uses: de-vri-es/setup-git-credentials@v2.0.8
         with:
           credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+
+      # - uses: actions/cache@v3
+      #   timeout-minutes: 5
+      #   with:
+      #     path: |
+      #       ~/.cache/go-build
+      #       ~/go/pkg/mod
+      #     key: ${{ runner.os }}-go-alpine-build-${{ hashFiles('**/go.sum') }}
+      #     restore-keys: |
+      #       ${{ runner.os }}-go-alpine-build
 
       - name: Build zetacored and zetaclientd
         env:
@@ -234,12 +242,12 @@ jobs:
             echo "Smoke Test Failed"
             exit 1
           fi
-    
+
       - name: Stop Private Network
         if: always()
         run: |
-            cd contrib/localnet/
-            docker compose down
+          cd contrib/localnet/
+          docker compose down
 
   upload:
     runs-on: ["zeta-runners"]
@@ -284,18 +292,6 @@ jobs:
           github_commit_sha: "${{ env.GIT_HASH }}"
           current_branch_name: "${{ steps.branch-name.outputs.current_branch }}"
 
-      - name: Check Upgrade Handler Name Matches Tag Name
-        if: ( startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release') ) && !endsWith(github.ref, '-rc')
-        run: |
-          UPGRADE_HANDLER_NAME=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
-          echo $UPGRADE_HANDLER_NAME
-          if [ ${{ github.ref_name }} != $UPGRADE_HANDLER_NAME ]; then
-            echo "ERROR: The name of this release (${{ github.ref_name }}) does not match the releaseVersion const in app/setup_handlers.go"
-            echo "Did you forget to update the 'releaseVersion' const in app/setup_handlers.go?" 
-            exit 1
-          fi
-          echo "releaseVersion' const in app/setup_handlers.go matches this tagged release - Moving Forward!"
-
       - uses: actions/download-artifact@v3
         with:
           name: binaries-${{ github.sha }}
@@ -307,10 +303,6 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
-
-      - name: Check Binaries
-        run: |
-          ls -lah
 
       - name: upload-files-to-s3
         uses: ./.github/actions/upload-to-s3
@@ -352,7 +344,7 @@ jobs:
           IMAGE_TAG: ${{ env.TAG_NAME }}
           GHCR_USERNAME: ${{ secrets.PAT_GITHUB_SERVICE_ACCT_USERNAME }}
           GHCR_TOKEN: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
-          
+
       - name: Create GitHub Release for ZetaCore/ZetaClient
         uses: softprops/action-gh-release@v1
         if: startsWith(github.ref, 'refs/tags/v')
@@ -369,21 +361,31 @@ jobs:
             zetaclientd-ubuntu-20-amd64
 
   upgrade_path_testing:
-    runs-on: ["buildjet-4vcpu-ubuntu-2204"]
+    runs-on: ["zeta-runners"]
     timeout-minutes: 60
     if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release')
     needs:
       - build-and-test
       - build-alpine-and-test
-      - upload
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
 
+      - name: Major Version in Upgrade Handler Must Match Tag
+        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release')
+        run: |
+          UPGRADE_HANDLER_MAJOR_VERSION=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"' | cut -d '.' -f1)
+          echo $UPGRADE_HANDLER_MAJOR_VERSION
+          GITHUB_TAG_MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d '.' -f1)
+          if [ $GITHUB_TAG_MAJOR_VERSION != $UPGRADE_HANDLER_MAJOR_VERSION ]; then
+            echo "ERROR: The major version of this release (${{ github.ref_name }}) does not match the major version in the releaseVersion constant ($UPGRADE_HANDLER_MAJOR_VERSION) found in app/setup_handlers.go"
+            echo "Did you forget to update the 'releaseVersion' in app/setup_handlers.go?" 
+            exit 1
+          fi
+          echo "The major version found in 'releaseVersion' in app/setup_handlers.go matches this tagged release - Moving Forward!"
+
       - name: upgrade-path-testing
         uses: ./.github/actions/upgrade-testing
         with:
           github_token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
-
-          
