Added missing dependencies to alpine build job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -5,7 +5,6 @@ on:
     branches:
       - develop
       - athens2-develop
-      - ledger-support-fix-ci
     tags:
       - "*"
   pull_request:
@@ -24,93 +23,93 @@ env:
   GITHUB_REF_NAME: "$(echo ${{ github.ref_name }} | tr '//' '-')"
 
 jobs:
-  # build-and-test:
-  #   strategy:
-  #     matrix:
-  #       runs-on:
-  #         [
-  #           buildjet-4vcpu-ubuntu-2204-arm,
-  #           buildjet-4vcpu-ubuntu-2204,
-  #           buildjet-4vcpu-ubuntu-2004,
-  #         ]
-  #   runs-on: ${{matrix.runs-on}}
-  #   timeout-minutes: 30
-  #   steps:
-  #     - uses: actions/checkout@v3
+  build-and-test:
+    strategy:
+      matrix:
+        runs-on:
+          [
+            buildjet-4vcpu-ubuntu-2204-arm,
+            buildjet-4vcpu-ubuntu-2204,
+            buildjet-4vcpu-ubuntu-2004,
+          ]
+    runs-on: ${{matrix.runs-on}}
+    timeout-minutes: 30
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Set CPU Architecture
-  #       shell: bash
-  #       run: |
-  #         if [ "$(uname -m)" == "aarch64" ]; then
-  #           echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-  #         elif [ "$(uname -m)" == "x86_64" ]; then
-  #           echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-  #         else
-  #           echo "Unsupported architecture" >&2
-  #           exit 1
-  #         fi
+      - name: Set CPU Architecture
+        shell: bash
+        run: |
+          if [ "$(uname -m)" == "aarch64" ]; then
+            echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+          elif [ "$(uname -m)" == "x86_64" ]; then
+            echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+          else
+            echo "Unsupported architecture" >&2
+            exit 1
+          fi
 
-  #     - name: Install Pipeline Dependencies
-  #       uses: ./.github/actions/install-dependencies
-  #       timeout-minutes: 8
-  #       with:
-  #         cpu_architecture: ${{ env.CPU_ARCH }}
-  #         skip_python: "true"
-  #         skip_aws_cli: "true"
-  #         skip_docker_compose: "true"
+      - name: Install Pipeline Dependencies
+        uses: ./.github/actions/install-dependencies
+        timeout-minutes: 8
+        with:
+          cpu_architecture: ${{ env.CPU_ARCH }}
+          skip_python: "true"
+          skip_aws_cli: "true"
+          skip_docker_compose: "true"
 
-  #     - name: setup-git-credentials
-  #       uses: de-vri-es/setup-git-credentials@v2.0.8
-  #       with:
-  #         credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+      - name: setup-git-credentials
+        uses: de-vri-es/setup-git-credentials@v2.0.8
+        with:
+          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-  #     # - uses: actions/cache@v3
-  #     #   timeout-minutes: 5
-  #     #   with:
-  #     #     path: |
-  #     #       ~/.cache/go-build
-  #     #       ~/go/pkg/mod
-  #     #     key: ${{ matrix.runs-on }}-go-${{ hashFiles('**/go.sum') }}
-  #     #     restore-keys: |
-  #     #       ${{ matrix.runs-on }}-go-
+      # - uses: actions/cache@v3
+      #   timeout-minutes: 5
+      #   with:
+      #     path: |
+      #       ~/.cache/go-build
+      #       ~/go/pkg/mod
+      #     key: ${{ matrix.runs-on }}-go-${{ hashFiles('**/go.sum') }}
+      #     restore-keys: |
+      #       ${{ matrix.runs-on }}-go-
 
-  #     - name: Build zetacored and zetaclientd
-  #       env:
-  #         CGO_ENABLED: 1
-  #         GOOS: linux
-  #         GOARCH: ${{ env.CPU_ARCH }}
-  #       run: |
-  #         make install-testnet
-  #         cp "$HOME"/go/bin/* ./
+      - name: Build zetacored and zetaclientd
+        env:
+          CGO_ENABLED: 1
+          GOOS: linux
+          GOARCH: ${{ env.CPU_ARCH }}
+        run: |
+          make install-testnet
+          cp "$HOME"/go/bin/* ./
 
-  #     - name: Test
-  #       run: |
-  #         echo "Running Build Tests"
-  #         make test
-  #         chmod a+x ./zetacored
-  #         ./zetacored version
+      - name: Test
+        run: |
+          echo "Running Build Tests"
+          make test
+          chmod a+x ./zetacored
+          ./zetacored version
 
-  #     - name: Name Binaries
-  #       if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-  #       env:
-  #         CPU_ARCH: ${{ env.CPU_ARCH }}
-  #       run: |
-  #         OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
-  #         cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
-  #         cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
+      - name: Name Binaries
+        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+        env:
+          CPU_ARCH: ${{ env.CPU_ARCH }}
+        run: |
+          OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
+          cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
+          cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
 
-  #     - name: Save Binaries as Artifacts
-  #       uses: actions/upload-artifact@v3
-  #       if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-  #       with:
-  #         name: binaries-${{ github.sha }}
-  #         path: |
-  #           zetacored-ubuntu-*
-  #           zetaclientd-ubuntu-*
+      - name: Save Binaries as Artifacts
+        uses: actions/upload-artifact@v3
+        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+        with:
+          name: binaries-${{ github.sha }}
+          path: |
+            zetacored-ubuntu-*
+            zetaclientd-ubuntu-*
 
   build-alpine-and-test:
     runs-on: ubuntu-latest
-    # if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
     timeout-minutes: 30
     steps:
       - uses: actions/checkout@v3
@@ -202,192 +201,192 @@ jobs:
             zetacored-alpine-*
             zetaclientd-alpine-*
 
-  # smoke-test:
-  #   runs-on: ["zeta-runners"]
-  #   timeout-minutes: 20
-  #   steps:
-  #     - uses: actions/checkout@v3
+  smoke-test:
+    runs-on: ["zeta-runners"]
+    timeout-minutes: 20
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: Set CPU Architecture
-  #       shell: bash
-  #       run: |
-  #         if [ "$(uname -m)" == "aarch64" ]; then
-  #           echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-  #         elif [ "$(uname -m)" == "x86_64" ]; then
-  #           echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-  #         else
-  #           echo "Unsupported architecture" >&2
-  #           exit 1
-  #         fi
+      - name: Set CPU Architecture
+        shell: bash
+        run: |
+          if [ "$(uname -m)" == "aarch64" ]; then
+            echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+          elif [ "$(uname -m)" == "x86_64" ]; then
+            echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+          else
+            echo "Unsupported architecture" >&2
+            exit 1
+          fi
 
-  #     - name: Install Pipeline Dependencies
-  #       uses: ./.github/actions/install-dependencies
-  #       timeout-minutes: 8
-  #       with:
-  #         cpu_architecture: ${{ env.CPU_ARCH }}
-  #         skip_python: "false"
-  #         skip_aws_cli: "true"
-  #         skip_docker_compose: "false"
+      - name: Install Pipeline Dependencies
+        uses: ./.github/actions/install-dependencies
+        timeout-minutes: 8
+        with:
+          cpu_architecture: ${{ env.CPU_ARCH }}
+          skip_python: "false"
+          skip_aws_cli: "true"
+          skip_docker_compose: "false"
 
-  #     - name: Start Private Network
-  #       run: |
-  #         make zetanode
-  #         cd contrib/localnet/ 
-  #         docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+      - name: Start Private Network
+        run: |
+          make zetanode
+          cd contrib/localnet/ 
+          docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
 
-  #     - name: Run Smoke Test
-  #       run: |
-  #         cd contrib/localnet
-  #         docker-compose up orchestrator --exit-code-from orchestrator
-  #         if [ $? -ne 0 ]; then
-  #           echo "Smoke Test Failed"
-  #           exit 1
-  #         fi
+      - name: Run Smoke Test
+        run: |
+          cd contrib/localnet
+          docker-compose up orchestrator --exit-code-from orchestrator
+          if [ $? -ne 0 ]; then
+            echo "Smoke Test Failed"
+            exit 1
+          fi
     
-  #     - name: Stop Private Network
-  #       if: always()
-  #       run: |
-  #           cd contrib/localnet/
-  #           docker compose down
+      - name: Stop Private Network
+        if: always()
+        run: |
+            cd contrib/localnet/
+            docker compose down
 
-  # upload:
-  #   runs-on: ["zeta-runners"]
-  #   timeout-minutes: 15
-  #   if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-  #   needs:
-  #     - build-and-test
-  #     - smoke-test
-  #     - build-alpine-and-test
-  #   steps:
-  #     - uses: actions/checkout@v3
+  upload:
+    runs-on: ["zeta-runners"]
+    timeout-minutes: 15
+    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+    needs:
+      - build-and-test
+      - smoke-test
+      - build-alpine-and-test
+    steps:
+      - uses: actions/checkout@v3
 
-  #     - name: setup-git-credentials
-  #       uses: de-vri-es/setup-git-credentials@v2.0.8
-  #       with:
-  #         credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+      - name: setup-git-credentials
+        uses: de-vri-es/setup-git-credentials@v2.0.8
+        with:
+          credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-  #     - name: Install Pipeline Dependencies
-  #       uses: ./.github/actions/install-dependencies
-  #       timeout-minutes: 8
-  #       with:
-  #         cpu_architecture: ${{ env.CPU_ARCH }}
-  #         skip_python: "true"
-  #         skip_aws_cli: "false"
-  #         skip_docker_compose: "true"
+      - name: Install Pipeline Dependencies
+        uses: ./.github/actions/install-dependencies
+        timeout-minutes: 8
+        with:
+          cpu_architecture: ${{ env.CPU_ARCH }}
+          skip_python: "true"
+          skip_aws_cli: "false"
+          skip_docker_compose: "true"
 
-  #     - name: Get branch name
-  #       id: branch-name
-  #       uses: tj-actions/branch-names@v6
+      - name: Get branch name
+        id: branch-name
+        uses: tj-actions/branch-names@v6
 
-  #     - name: Git Hash
-  #       run: |
-  #         echo "GIT_HASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
-  #         echo "WORKSPACE_DIR=$(pwd)" >> ${GITHUB_ENV}
+      - name: Git Hash
+        run: |
+          echo "GIT_HASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
+          echo "WORKSPACE_DIR=$(pwd)" >> ${GITHUB_ENV}
 
-  #     - name: set-branch-name
-  #       uses: ./.github/actions/set-branch-name
-  #       with:
-  #         github_ref: "${{github.ref}}"
-  #         github_event: "${{ github.event_name }}"
-  #         github_head_ref: "${{ github.event.pull_request.head.ref }}"
-  #         github_commit_sha: "${{ env.GIT_HASH }}"
-  #         current_branch_name: "${{ steps.branch-name.outputs.current_branch }}"
+      - name: set-branch-name
+        uses: ./.github/actions/set-branch-name
+        with:
+          github_ref: "${{github.ref}}"
+          github_event: "${{ github.event_name }}"
+          github_head_ref: "${{ github.event.pull_request.head.ref }}"
+          github_commit_sha: "${{ env.GIT_HASH }}"
+          current_branch_name: "${{ steps.branch-name.outputs.current_branch }}"
 
-  #     - name: Check Upgrade Handler Name Matches Tag Name
-  #       if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release')
-  #       run: |
-  #         UPGRADE_HANDLER_NAME=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
-  #         echo $UPGRADE_HANDLER_NAME
-  #         if [ ${{ github.ref_name }} != $UPGRADE_HANDLER_NAME ]; then
-  #           echo "ERROR: The name of this release (${{ github.ref_name }}) does not match the releaseVersion const in app/setup_handlers.go"
-  #           echo "Did you forget to update the 'releaseVersion' const in app/setup_handlers.go?" 
-  #           exit 1
-  #         fi
-  #         echo "releaseVersion' const in app/setup_handlers.go matches this tagged release - Moving Forward!"
+      - name: Check Upgrade Handler Name Matches Tag Name
+        if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/release')
+        run: |
+          UPGRADE_HANDLER_NAME=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
+          echo $UPGRADE_HANDLER_NAME
+          if [ ${{ github.ref_name }} != $UPGRADE_HANDLER_NAME ]; then
+            echo "ERROR: The name of this release (${{ github.ref_name }}) does not match the releaseVersion const in app/setup_handlers.go"
+            echo "Did you forget to update the 'releaseVersion' const in app/setup_handlers.go?" 
+            exit 1
+          fi
+          echo "releaseVersion' const in app/setup_handlers.go matches this tagged release - Moving Forward!"
 
-  #     - uses: actions/download-artifact@v3
-  #       with:
-  #         name: binaries-${{ github.sha }}
-  #         path: ./
+      - uses: actions/download-artifact@v3
+        with:
+          name: binaries-${{ github.sha }}
+          path: ./
 
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v1
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ env.AWS_REGION }}
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
 
-  #     - name: upload-files-to-s3
-  #       uses: ./.github/actions/upload-to-s3
-  #       with:
-  #         bucket-name: ${{ env.S3_BUCKET_PATH }}
-  #         release-name: ${{ env.RELEASE_NAME }}
-  #         git-sha: ${{ github.sha }}
-  #         files: |
-  #           zetacored-alpine-amd64
-  #           zetaclientd-alpine-amd64
-  #           zetacored-ubuntu-22-arm64
-  #           zetaclientd-ubuntu-22-arm64
-  #           zetacored-ubuntu-22-amd64
-  #           zetaclientd-ubuntu-22-amd64
-  #           zetacored-ubuntu-20-amd64
-  #           zetaclientd-ubuntu-20-amd64
+      - name: upload-files-to-s3
+        uses: ./.github/actions/upload-to-s3
+        with:
+          bucket-name: ${{ env.S3_BUCKET_PATH }}
+          release-name: ${{ env.RELEASE_NAME }}
+          git-sha: ${{ github.sha }}
+          files: |
+            zetacored-alpine-amd64
+            zetaclientd-alpine-amd64
+            zetacored-ubuntu-22-arm64
+            zetaclientd-ubuntu-22-arm64
+            zetacored-ubuntu-22-amd64
+            zetaclientd-ubuntu-22-amd64
+            zetacored-ubuntu-20-amd64
+            zetaclientd-ubuntu-20-amd64
 
-  #     # # Approval will be required closer to mainnet
-  #     # - name: Require Approval To Create a Release
-  #     #   uses: softprops/action-gh-release@v1
-  #     #   if: startsWith(github.ref, 'refs/tags/v')
-  #     #   with:
-  #     #     token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
-  #     #     files: |
-  #     # zetacored-alpine-amd64
-  #     # zetaclientd-alpine-amd64
-  #     # zetacored-ubuntu-22-arm64
-  #     # zetaclientd-ubuntu-22-arm64
-  #     # zetacored-ubuntu-22-amd64
-  #     # zetaclientd-ubuntu-22-amd64
-  #     # zetacored-ubuntu-20-amd64
-  #     # zetaclientd-ubuntu-20-amd64
+      # # Approval will be required closer to mainnet
+      # - name: Require Approval To Create a Release
+      #   uses: softprops/action-gh-release@v1
+      #   if: startsWith(github.ref, 'refs/tags/v')
+      #   with:
+      #     token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+      #     files: |
+      # zetacored-alpine-amd64
+      # zetaclientd-alpine-amd64
+      # zetacored-ubuntu-22-arm64
+      # zetaclientd-ubuntu-22-arm64
+      # zetacored-ubuntu-22-amd64
+      # zetaclientd-ubuntu-22-amd64
+      # zetacored-ubuntu-20-amd64
+      # zetaclientd-ubuntu-20-amd64
 
-  #     - name: Build, tag, and push docker images
-  #       uses: ./.github/actions/build-docker-images
-  #       with:
-  #         DOCKER_FILENAME: Dockerfile
-  #         REPOSITORY_NAME: zeta-node
-  #         IMAGE_TAG: ${{ env.TAG_NAME }}
-  #         GHCR_USERNAME: ${{ secrets.PAT_GITHUB_SERVICE_ACCT_USERNAME }}
-  #         GHCR_TOKEN: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+      - name: Build, tag, and push docker images
+        uses: ./.github/actions/build-docker-images
+        with:
+          DOCKER_FILENAME: Dockerfile
+          REPOSITORY_NAME: zeta-node
+          IMAGE_TAG: ${{ env.TAG_NAME }}
+          GHCR_USERNAME: ${{ secrets.PAT_GITHUB_SERVICE_ACCT_USERNAME }}
+          GHCR_TOKEN: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
           
-  #     - name: Create GitHub Release for ZetaCore/ZetaClient
-  #       uses: softprops/action-gh-release@v1
-  #       if: startsWith(github.ref, 'refs/tags/v')
-  #       with:
-  #         token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
-  #         files: |
-  #           zetacored-alpine-amd64
-  #           zetaclientd-alpine-amd64
-  #           zetacored-ubuntu-22-arm64
-  #           zetaclientd-ubuntu-22-arm64
-  #           zetacored-ubuntu-22-amd64
-  #           zetaclientd-ubuntu-22-amd64
-  #           zetacored-ubuntu-20-amd64
-  #           zetaclientd-ubuntu-20-amd64
+      - name: Create GitHub Release for ZetaCore/ZetaClient
+        uses: softprops/action-gh-release@v1
+        if: startsWith(github.ref, 'refs/tags/v')
+        with:
+          token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+          files: |
+            zetacored-alpine-amd64
+            zetaclientd-alpine-amd64
+            zetacored-ubuntu-22-arm64
+            zetaclientd-ubuntu-22-arm64
+            zetacored-ubuntu-22-amd64
+            zetaclientd-ubuntu-22-amd64
+            zetacored-ubuntu-20-amd64
+            zetaclientd-ubuntu-20-amd64
 
-  # upgrade_path_testing:
-  #   runs-on: ["zeta-runners"]
-  #   timeout-minutes: 60
-  #   if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-  #   needs:
-  #     - build-and-test
-  #     - build-alpine-and-test
-  #   steps:
-  #     - uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
+  upgrade_path_testing:
+    runs-on: ["zeta-runners"]
+    timeout-minutes: 60
+    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+    needs:
+      - build-and-test
+      - build-alpine-and-test
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-  #     - name: upgrade-path-testing
-  #       uses: ./.github/actions/upgrade-testing
-  #       with:
-  #         github_token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+      - name: upgrade-path-testing
+        uses: ./.github/actions/upgrade-testing
+        with:
+          github_token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
           
