testing goreleaser

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -58,7 +58,104 @@ jobs:
           touch .release-env
           make release
 
+        build-alpine-and-test:
+          runs-on: ["ubuntu-latest"]
+          timeout-minutes: 30
+          concurrency:
+            group: "alpine-build-test"
+          steps:
+            - uses: actions/checkout@v3
+      
+            - name: Set CPU Architecture
+              shell: bash
+              run: |
+                if [ "$(uname -m)" == "aarch64" ]; then
+                  echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+                elif [ "$(uname -m)" == "x86_64" ]; then
+                  echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+                else
+                  echo "Unsupported architecture" >&2
+                  exit 1
+                fi
+      
+            - name: Install Pipeline Dependencies
+              uses: ./.github/actions/install-dependencies
+              timeout-minutes: 8
+              with:
+                cpu_architecture: ${{ env.CPU_ARCH }}
+                skip_python: "true"
+                skip_aws_cli: "true"
+                skip_docker_compose: "false"
+      
+            - uses: jirutka/setup-alpine@v1
+              with:
+                branch: v3.17
+                arch: x86_64
+                packages: >
+                  build-base
+                  pkgconf
+                  lld
+                  go
+                  gcc 
+                  g++
+                  libusb-dev 
+                  linux-headers
+                  git
+                shell-name: alpine.sh
+      
+            - name: Build zetacored and zetaclientd
+              env:
+                CGO_ENABLED: 1
+                GOOS: linux
+                GOARCH: ${{ env.CPU_ARCH }}
+              shell: alpine.sh --root {0}
+              run: |
+                git config --global --add safe.directory '*'
+                make install-testnet
+                cp "$HOME"/go/bin/* ./
+      
+            - name: Binary Docker Test
+              env:
+                CPU_ARCH: ${{ env.CPU_ARCH }}
+              shell: alpine.sh --root {0}
+              run: |
+                chmod a+x ./zetacored
+                ./zetacored version
+                mv zetacored zetacored-alpine-$CPU_ARCH
+                mv zetaclientd zetaclientd-alpine-$CPU_ARCH
 
+              - name: Create GitHub Release
+                uses: softprops/action-gh-release@v1
+                with:
+                  token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+                  generate_release_notes: true
+                  files: |
+                    dist/checksums.txt
+                    dist/zetacored*/**
+                    dist/zetaclientd*/**
+      
+            # - name: Save Binaries as Artifacts
+            #   if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+            #   uses: actions/upload-artifact@v3
+            #   with:
+            #     name: binaries-${{ github.sha }}
+            #     path: |
+            #       zetacored-alpine-*
+            #       zetaclientd-alpine-*
+                  
+            - name: Clean Up Alpine Workspace
+              if: always()
+              shell: alpine.sh --root {0}
+              run: |
+                set -e # fail on error
+                rm -rf *
+              
+            - name: Clean Up Workspace
+              if: always()
+              shell: bash
+              run: rm -rf *
+
+                
   # announce-release:
   #   # runs-on: buildjet-2vcpu-ubuntu-2004
   #   runs-on: ubuntu-latest
