WIP: try change build.yml to adapt to new docker compose file

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -228,15 +228,17 @@ jobs:
 
       - name: Start Private Network
         run: |
-          cd contrib/localnet
-          docker compose down || echo "not running or error"
-          docker compose build zetacore0 eth && docker compose build orchestrator
-          docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+          make zetanode
+#          cd contrib/localnet
+#          docker compose down || echo "not running or error"
+#          docker compose build zetacore0 eth && docker compose build orchestrator
+#          docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
 
       - name: Run Smoke Test
         run: |
-          cd contrib/localnet
-          docker-compose up orchestrator --exit-code-from orchestrator
+#          cd contrib/localnet
+#          docker-compose up orchestrator --exit-code-from orchestrator
+          make start-smoketest
           if [ $? -ne 0 ]; then
             echo "Smoke Test Failed"
             exit 1
