testing combo arm and amd

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -24,15 +24,12 @@ env:
   GITHUB_REF_NAME: "$(echo ${{ github.ref_name }} | tr '//' '-')"
 
 jobs:
-
   build-and-test:
     strategy:
       matrix:
-        runs-on: [buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm ]
-        # [buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204 ]
+        runs-on: [buildjet-4vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204 ]
     runs-on: ${{matrix.runs-on}}
     timeout-minutes: 30
-
     steps:
     - uses: actions/checkout@v3
 
@@ -50,25 +47,27 @@ jobs:
 
     - name: Install Pipeline Dependencies
       uses:  ./.github/actions/install-dependencies
+      timeout-minutes: 8 
       with:
         cpu_architecture: ${{ env.CPU_ARCH }}
         skip_python: "true"
         skip_aws_cli: "true"
         skip_docker_compose: "true"
 
+
     - name: setup-git-credentials
       uses: de-vri-es/setup-git-credentials@v2.0.8
       with:
         credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-    # - uses: actions/cache@v3
-    #   with:
-    #     path: |
-    #       ~/.cache/go-build
-    #       ~/go/pkg/mod
-    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-    #     restore-keys: |
-    #       ${{ runner.os }}-go-
+    - uses: actions/cache@v3
+      with:
+        path: |
+          ~/.cache/go-build
+          ~/go/pkg/mod
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: |
+          ${{ runner.os }}-go-
 
     - name: Build zetacored and zetaclientd
       env:
@@ -104,140 +103,144 @@ jobs:
             zetacored-ubuntu-*
             zetaclientd-ubuntu-*
 
-  # build-alpine-and-test:
-  #   runs-on: ubuntu-latest
-  #   timeout-minutes: 30
-  #   steps:
+  build-alpine-and-test:
+    runs-on: buildjet-4vcpu-ubuntu-2204 # [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]#ubuntu-latest
+    timeout-minutes: 30
+    steps:
 
-  #   - uses: actions/checkout@v3
+    - uses: actions/checkout@v3
 
-  #   - name: Set CPU Architecture
-  #     shell: bash
-  #     run: |
-  #       if [ "$(uname -m)" == "aarch64" ]; then
-  #         echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-  #       elif [ "$(uname -m)" == "x86_64" ]; then
-  #         echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-  #       else
-  #         echo "Unsupported architecture" >&2
-  #         exit 1
-  #       fi
+    - name: Set CPU Architecture
+      shell: bash
+      run: |
+        if [ "$(uname -m)" == "aarch64" ]; then
+          echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+        elif [ "$(uname -m)" == "x86_64" ]; then
+          echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+        else
+          echo "Unsupported architecture" >&2
+          exit 1
+        fi
 
-  #   - name: Install Pipeline Dependencies
-  #     uses:  ./.github/actions/install-dependencies
-  #     with:
-  #       cpu_architecture: ${{ env.CPU_ARCH }}
-  #       skip_python: "true"
-  #       skip_aws_cli: "true"
-  #       skip_docker_compose: "false"
+    - name: Install Pipeline Dependencies
+      uses:  ./.github/actions/install-dependencies
+      timeout-minutes: 8 
+      with:
+        cpu_architecture: ${{ env.CPU_ARCH }}
+        skip_python: "true"
+        skip_aws_cli: "true"
+        skip_docker_compose: "false"
 
-  #   - uses: jirutka/setup-alpine@v1
-  #     with:
-  #       arch: x86_64
-  #       packages: >
-  #         build-base
-  #         pkgconf
-  #         lld
-  #         go 
-  #         gcc 
-  #         g++
-  #       shell-name: alpine.sh
 
-  #   - name: setup-git-credentials
-  #     uses: de-vri-es/setup-git-credentials@v2.0.8
-  #     with:
-  #       credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+    - uses: jirutka/setup-alpine@v1
+      with:
+        arch: x86_64
+        packages: >
+          build-base
+          pkgconf
+          lld
+          go 
+          gcc 
+          g++
+        shell-name: alpine.sh
 
-  #   - uses: actions/cache@v3
-  #     with:
-  #       path: |
-  #         ~/.cache/go-build
-  #         ~/go/pkg/mod
-  #       key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-  #       restore-keys: |
-  #         ${{ runner.os }}-go-
+    - name: setup-git-credentials
+      uses: de-vri-es/setup-git-credentials@v2.0.8
+      with:
+        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-  #   - name: Build zetacored and zetaclientd
-  #     env:
-  #       CGO_ENABLED: 1
-  #       GOOS: linux
-  #       GOARCH: ${{ env.CPU_ARCH }}
-  #     shell: alpine.sh --root {0}
-  #     run: |
-  #       apk add --no-cache --update
-  #       go mod tidy
-  #       make install-testnet
-  #       cp "$HOME"/go/bin/* ./
+    - uses: actions/cache@v3
+      with:
+        path: |
+          ~/.cache/go-build
+          ~/go/pkg/mod
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: |
+          ${{ runner.os }}-go-
 
-  #   - name: Test
-  #     shell: alpine.sh --root {0}
-  #     run: |
-  #       echo "Running Build Tests"
-  #       go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
+    - name: Build zetacored and zetaclientd
+      env:
+        CGO_ENABLED: 1
+        GOOS: linux
+        GOARCH: ${{ env.CPU_ARCH }}
+      shell: alpine.sh --root {0}
+      run: |
+        apk add --no-cache --update
+        go mod tidy
+        make install-testnet
+        cp "$HOME"/go/bin/* ./
 
-  #   - name: Binary Docker Test
-  #     shell: alpine.sh --root {0}
-  #     run: |
-  #       chmod a+x ./zetacored
-  #       ./zetacored version
-  #       mv zetacored zetacored-alpine
-  #       mv zetaclientd zetaclientd-alpine
+    - name: Test
+      shell: alpine.sh --root {0}
+      run: |
+        echo "Running Build Tests"
+        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
 
-  #   - name: Save Binaries as Artifacts
-  #     if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-  #     uses: actions/upload-artifact@v3
-  #     with:
-  #       name: binaries-${{ github.sha }}
-  #       path: |
-  #           zetacored-alpine
-  #           zetaclientd-alpine
+    - name: Binary Docker Test
+      shell: alpine.sh --root {0}
+      run: |
+        chmod a+x ./zetacored
+        ./zetacored version
+        mv zetacored zetacored-alpine
+        mv zetaclientd zetaclientd-alpine
 
-#   smoke-test:
-#     strategy:
-#       matrix:
-#         runs-on: [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ] #[buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ] # [ buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm ] # [buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ]
-#         # [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]
-#     runs-on: ${{matrix.runs-on}}
-# #   runs-on: ["zeta-runners"]
-#     timeout-minutes: 30
-#     steps:
-#     - uses: actions/checkout@v3
+    - name: Save Binaries as Artifacts
+      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+      uses: actions/upload-artifact@v3
+      with:
+        name: binaries-${{ github.sha }}
+        path: |
+            zetacored-alpine
+            zetaclientd-alpine
 
-#     - name: Set CPU Architecture
-#       shell: bash
-#       run: |
-#         if [ "$(uname -m)" == "aarch64" ]; then
-#           echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-#         elif [ "$(uname -m)" == "x86_64" ]; then
-#           echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-#         else
-#           echo "Unsupported architecture" >&2
-#           exit 1
-#         fi
+  smoke-test:
+    # strategy:
+    #   matrix:
+    #     runs-on: [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ] #[buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ] # [ buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm ] # [buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ]
+    #     # [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]
+    # runs-on: ${{matrix.runs-on}}
+    runs-on:  buildjet-4vcpu-ubuntu-2204 # ["zeta-runners"]
+    timeout-minutes: 30
+    steps:
+    - uses: actions/checkout@v3
 
-#     - name: Install Pipeline Dependencies
-#       uses:  ./.github/actions/install-dependencies
-#       with:
-#         cpu_architecture: ${{ env.CPU_ARCH }}
-#         # skip_python: "false"
-#         skip_aws_cli: "true"
-#         # skip_docker_compose: "false"
+    - name: Set CPU Architecture
+      shell: bash
+      run: |
+        if [ "$(uname -m)" == "aarch64" ]; then
+          echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+        elif [ "$(uname -m)" == "x86_64" ]; then
+          echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+        else
+          echo "Unsupported architecture" >&2
+          exit 1
+        fi
 
-#     - name: Start Private Network
-#       run: |
-#         cd contrib/localnet
-#         docker compose down || echo "not running or error"
-#         docker compose build zetacore0 eth && docker compose build orchestrator
-#         docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+    - name: Install Pipeline Dependencies
+      uses:  ./.github/actions/install-dependencies
+      timeout-minutes: 8 
+      with:
+        cpu_architecture: ${{ env.CPU_ARCH }}
+        skip_python: "false"
+        skip_aws_cli: "true"
+        skip_docker_compose: "false"
+        
 
-#     - name: Run Smoke Test
-#       run: |
-#         cd contrib/localnet
-#         docker-compose up orchestrator --exit-code-from orchestrator
-#         if [ $? -ne 0 ]; then
-#           echo "Smoke Test Failed"
-#           exit 1
-#         fi
+    - name: Start Private Network
+      run: |
+        cd contrib/localnet
+        docker compose down || echo "not running or error"
+        docker compose build zetacore0 eth && docker compose build orchestrator
+        docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+
+    - name: Run Smoke Test
+      run: |
+        cd contrib/localnet
+        docker-compose up orchestrator --exit-code-from orchestrator
+        if [ $? -ne 0 ]; then
+          echo "Smoke Test Failed"
+          exit 1
+        fi
 
 #   # upload:
 #   #   runs-on: ["zeta-runners"]
