rightsizing instance for smoketest

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -25,161 +25,84 @@ env:
 
 jobs:
 
-  build-and-test-ARM:
-    strategy:
-      matrix:
-        runs-on: [buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ] # [ buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm ] # [buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ]
-    runs-on: ${{matrix.runs-on}}
-    timeout-minutes: 30
+  # build-and-test:
+  #   strategy:
+  #     matrix:
+  #       runs-on: [buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm ]
+  #       # [buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204 ]
+  #   runs-on: ${{matrix.runs-on}}
+  #   timeout-minutes: 30
 
-    steps:
-    - uses: actions/checkout@v3
+  #   steps:
+  #   - uses: actions/checkout@v3
 
-    - name: set cpu architecture
-      shell: bash
-      run: |
-        if [ "$(uname -m)" == "aarch64" ]; then
-          echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-        elif [ "$(uname -m)" == "x86_64" ]; then
-          echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-        else
-          echo "Unsupported architecture" >&2
-          exit 1
-        fi
+  #   - name: Set CPU Architecture
+  #     shell: bash
+  #     run: |
+  #       if [ "$(uname -m)" == "aarch64" ]; then
+  #         echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+  #       elif [ "$(uname -m)" == "x86_64" ]; then
+  #         echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+  #       else
+  #         echo "Unsupported architecture" >&2
+  #         exit 1
+  #       fi
 
-    - name: Install Pipeline Dependencies
-      uses:  ./.github/actions/install-dependencies
-      with:
-        cpu_architecture: ${{ env.CPU_ARCH }}
-        skip_python: "true"
-        skip_aws_cli: "true"
-        skip_docker_compose: "true"
+  #   - name: Install Pipeline Dependencies
+  #     uses:  ./.github/actions/install-dependencies
+  #     with:
+  #       cpu_architecture: ${{ env.CPU_ARCH }}
+  #       skip_python: "true"
+  #       skip_aws_cli: "true"
+  #       skip_docker_compose: "true"
 
-    - name: setup-git-credentials
-      uses: de-vri-es/setup-git-credentials@v2.0.8
-      with:
-        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
+  #   - name: setup-git-credentials
+  #     uses: de-vri-es/setup-git-credentials@v2.0.8
+  #     with:
+  #       credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-    # - uses: actions/cache@v3
-    #   with:
-    #     path: |
-    #       ~/.cache/go-build
-    #       ~/go/pkg/mod
-    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-    #     restore-keys: |
-    #       ${{ runner.os }}-go-
+  #   # - uses: actions/cache@v3
+  #   #   with:
+  #   #     path: |
+  #   #       ~/.cache/go-build
+  #   #       ~/go/pkg/mod
+  #   #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+  #   #     restore-keys: |
+  #   #       ${{ runner.os }}-go-
 
-    - name: Build zetacored and zetaclientd
-      env:
-        CGO_ENABLED: 1
-        GOOS: linux
-        GOARCH: ${{ env.CPU_ARCH }}
-      run: |
-        make install-testnet
-        cp "$HOME"/go/bin/* ./
+  #   - name: Build zetacored and zetaclientd
+  #     env:
+  #       CGO_ENABLED: 1
+  #       GOOS: linux
+  #       GOARCH: ${{ env.CPU_ARCH }}
+  #     run: |
+  #       make install-testnet
+  #       cp "$HOME"/go/bin/* ./
 
-    - name: Test
-      run: |
-        echo "Running Build Tests"
-        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
-        chmod a+x ./zetacored
-        ./zetacored version
+  #   - name: Test
+  #     run: |
+  #       echo "Running Build Tests"
+  #       go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
+  #       chmod a+x ./zetacored
+  #       ./zetacored version
 
-    - name: Name Binaries
-      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-      env: 
-        CPU_ARCH: ${{ env.CPU_ARCH }}
-      run: |
-        OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
-        cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
-        cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
+  #   - name: Name Binaries
+  #     if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+  #     env: 
+  #       CPU_ARCH: ${{ env.CPU_ARCH }}
+  #     run: |
+  #       OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
+  #       cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
+  #       cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
 
-    - name: Save Binaries as Artifacts
-      uses: actions/upload-artifact@v3
-      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-      with:
-        name: binaries-${{ github.sha }}
-        path: |
-            zetacored-ubuntu-*
-            zetaclientd-ubuntu-*
-
-  build-and-test-AMD64:
-    strategy:
-      matrix:
-        runs-on: [buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204, buildjet-32vcpu-ubuntu-2204]
-    runs-on: ${{matrix.runs-on}}
-    timeout-minutes: 30
-
-    steps:
-    - uses: actions/checkout@v3
-
-    - name: set cpu architecture
-      shell: bash
-      run: |
-        if [ "$(uname -m)" == "aarch64" ]; then
-          echo "CPU_ARCH=arm64" >> $GITHUB_ENV
-        elif [ "$(uname -m)" == "x86_64" ]; then
-          echo "CPU_ARCH=amd64" >> $GITHUB_ENV
-        else
-          echo "Unsupported architecture" >&2
-          exit 1
-        fi
-
-    - name: Install Pipeline Dependencies
-      uses:  ./.github/actions/install-dependencies
-      with:
-        cpu_architecture: ${{ env.CPU_ARCH }}
-        skip_python: "true"
-        skip_aws_cli: "true"
-        skip_docker_compose: "true"
-
-    - name: setup-git-credentials
-      uses: de-vri-es/setup-git-credentials@v2.0.8
-      with:
-        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
-
-    # - uses: actions/cache@v3
-    #   with:
-    #     path: |
-    #       ~/.cache/go-build
-    #       ~/go/pkg/mod
-    #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-    #     restore-keys: |
-    #       ${{ runner.os }}-go-
-
-    - name: Build zetacored and zetaclientd
-      env:
-        CGO_ENABLED: 1
-        GOOS: linux
-        GOARCH: ${{ env.CPU_ARCH }}
-      run: |
-        make install-testnet
-        cp "$HOME"/go/bin/* ./
-
-    - name: Test
-      run: |
-        echo "Running Build Tests"
-        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
-        chmod a+x ./zetacored
-        ./zetacored version
-
-    - name: Name Binaries
-      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-      env: 
-        CPU_ARCH: ${{ env.CPU_ARCH }}
-      run: |
-        OS_VERSION=$(cat /etc/lsb-release | grep DISTRIB_RELEASE | cut -d '=' -f 2 | cut -d '.' -f 1)
-        cp zetacored zetacored-ubuntu-$OS_VERSION-$CPU_ARCH
-        cp zetaclientd zetaclientd-ubuntu-$OS_VERSION-$CPU_ARCH
-
-    - name: Save Binaries as Artifacts
-      uses: actions/upload-artifact@v3
-      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
-      with:
-        name: binaries-${{ github.sha }}
-        path: |
-            zetacored-ubuntu-*
-            zetaclientd-ubuntu-*
+  #   - name: Save Binaries as Artifacts
+  #     uses: actions/upload-artifact@v3
+  #     if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
+  #     with:
+  #       name: binaries-${{ github.sha }}
+  #       path: |
+  #           zetacored-ubuntu-*
+  #           zetaclientd-ubuntu-*
 
   # build-alpine-and-test:
   #   runs-on: ubuntu-latest
@@ -188,8 +111,25 @@ jobs:
 
   #   - uses: actions/checkout@v3
 
+  #   - name: Set CPU Architecture
+  #     shell: bash
+  #     run: |
+  #       if [ "$(uname -m)" == "aarch64" ]; then
+  #         echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+  #       elif [ "$(uname -m)" == "x86_64" ]; then
+  #         echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+  #       else
+  #         echo "Unsupported architecture" >&2
+  #         exit 1
+  #       fi
+
   #   - name: Install Pipeline Dependencies
   #     uses:  ./.github/actions/install-dependencies
+  #     with:
+  #       cpu_architecture: ${{ env.CPU_ARCH }}
+  #       skip_python: "true"
+  #       skip_aws_cli: "true"
+  #       skip_docker_compose: "false"
 
   #   - uses: jirutka/setup-alpine@v1
   #     with:
@@ -221,7 +161,7 @@ jobs:
   #     env:
   #       CGO_ENABLED: 1
   #       GOOS: linux
-  #       GOARCH: amd64
+  #       GOARCH: ${{ env.CPU_ARCH }}
   #     shell: alpine.sh --root {0}
   #     run: |
   #       apk add --no-cache --update
@@ -230,7 +170,6 @@ jobs:
   #       cp "$HOME"/go/bin/* ./
 
   #   - name: Test
-  #     if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
   #     shell: alpine.sh --root {0}
   #     run: |
   #       echo "Running Build Tests"
@@ -245,6 +184,7 @@ jobs:
   #       mv zetaclientd zetaclientd-alpine
 
   #   - name: Save Binaries as Artifacts
+  #     if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/develop')
   #     uses: actions/upload-artifact@v3
   #     with:
   #       name: binaries-${{ github.sha }}
@@ -252,32 +192,52 @@ jobs:
   #           zetacored-alpine
   #           zetaclientd-alpine
 
-  # smoke-test:
-  #   runs-on: ["zeta-runners"]
-  #   timeout-minutes: 30
-  #   steps:
-  #   - uses: actions/checkout@v3
+  smoke-test:
+    strategy:
+      matrix:
+        runs-on: [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ] #[buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ] # [ buildjet-8vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204-arm ] # [buildjet-2vcpu-ubuntu-2204-arm, buildjet-4vcpu-ubuntu-2204-arm, buildjet-8vcpu-ubuntu-2204-arm, buildjet-16vcpu-ubuntu-2204-arm, buildjet-32vcpu-ubuntu-2204-arm ]
+        # [ buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204 ]
+    runs-on: ${{matrix.runs-on}}
+#   runs-on: ["zeta-runners"]
+    timeout-minutes: 30
+    steps:
+    - uses: actions/checkout@v3
 
-  #   - name: Install Pipeline Dependencies
-  #     uses:  ./.github/actions/install-dependencies
+    - name: Set CPU Architecture
+      shell: bash
+      run: |
+        if [ "$(uname -m)" == "aarch64" ]; then
+          echo "CPU_ARCH=arm64" >> $GITHUB_ENV
+        elif [ "$(uname -m)" == "x86_64" ]; then
+          echo "CPU_ARCH=amd64" >> $GITHUB_ENV
+        else
+          echo "Unsupported architecture" >&2
+          exit 1
+        fi
 
-  #   - name: Start Private Network
-  #     if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-  #     run: |
-  #       cd contrib/localnet
-  #       docker compose down || echo "not running or error"
-  #       docker compose build zetacore0 eth && docker compose build orchestrator
-  #       docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+    - name: Install Pipeline Dependencies
+      uses:  ./.github/actions/install-dependencies
+      with:
+        cpu_architecture: ${{ env.CPU_ARCH }}
+        # skip_python: "false"
+        skip_aws_cli: "true"
+        # skip_docker_compose: "false"
 
-  #   - name: Run Smoke Test
-  #     if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-  #     run: |
-  #       cd contrib/localnet
-  #       docker-compose up orchestrator --exit-code-from orchestrator
-  #       if [ $? -ne 0 ]; then
-  #         echo "Smoke Test Failed"
-  #         exit 1
-  #       fi
+    - name: Start Private Network
+      run: |
+        cd contrib/localnet
+        docker compose down || echo "not running or error"
+        docker compose build zetacore0 eth && docker compose build orchestrator
+        docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+
+    - name: Run Smoke Test
+      run: |
+        cd contrib/localnet
+        docker-compose up orchestrator --exit-code-from orchestrator
+        if [ $? -ne 0 ]; then
+          echo "Smoke Test Failed"
+          exit 1
+        fi
 
   # upload:
   #   runs-on: ["zeta-runners"]
@@ -345,6 +305,8 @@ jobs:
   #       release-name: ${{ env.RELEASE_NAME }}
   #       git-sha: ${{ github.sha }}
   #       files: |
+  #         zetacored-ubuntu-*
+  #         zetaclientd-ubuntu-*
   #         zetacored-ubuntu-22-amd64
   #         zetaclientd-ubuntu-22-amd64
   #         zetacored-ubuntu-22-arm64
@@ -377,6 +339,8 @@ jobs:
   #     with:
   #       token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
   #       files: |
+  #         zetacored-*
+  #         zetaclientd-*
   #         zetacored-ubuntu
   #         zetaclientd-ubuntu
   #         zetacored-alpine
