Updating build steps

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -12,6 +12,11 @@ on:
     branches: 
       - develop
       - athens2-develop 
+    types: 
+      - synchronize
+      - opened
+      - reopened
+      - ready_for_review
 
 env:
   S3_BUCKET_NAME: "zetachain-deployment-files"
@@ -19,30 +24,17 @@ env:
   GITHUB_REF_NAME: "$(echo ${{ github.ref_name }} | tr '//' '-')"
 
 jobs:
-  build-and-upload:
+  build-and-test:
     runs-on: ubuntu-latest
+    timeout-minutes: 30
     steps:
+
     - uses: actions/checkout@v3
 
     - name: setup-git-credentials
       uses: de-vri-es/setup-git-credentials@v2.0.8
       with:
-        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
-
-
-    - name: Get branch name
-      id: branch-name
-      uses: tj-actions/branch-names@v6
-
-    - name: Set branch name
-      id: set-branch-name
-      run: |
-        if [ ${{ github.event_name }} == "pull_request" ]; then
-          echo "Setting the current branch name to same as the source branch of the PR"
-          echo "RELEASE_NAME=${{ steps.branch-name.outputs.head_ref_branch }}" >> $GITHUB_ENV
-        else
-          echo "RELEASE_NAME=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
-        fi
+        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
     - uses: actions/cache@v3
       with:
@@ -58,26 +50,104 @@ jobs:
         make install
         cp "$HOME"/go/bin/* ./
 
-    # - name: Test
-    #   if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-    #   run: |
-    #     echo "Running Build Tests"
-    #     #make test
-    #     go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
-
-    - name: Build Zetavisor
-      if: false # Not needed - Building cosmovisor should be part of the zetavisor repo
+    - name: Test
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
       run: |
-        go get github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/cosmovisor@zetavisor-v0.1.2
-        go install github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/cosmovisor@zetavisor-v0.1.2
-        cp "$HOME"/go/bin/cosmovisor ./cosmovisor
+        echo "Running Build Tests"
+        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
 
-    - name: Install AWS CLI # Used for local testing of Git Actions
-      if: ${{ env.ACT }}
+    - name: Save Binaries as Artifacts
+      uses: actions/upload-artifact@v3
+      with:
+        name: binaries-${{ github.sha }}
+        path: |
+            zetacored
+            zetaclientd
+        
+  smoke-test:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: install-docker-compose
+      uses: ./.github/actions/install-docker-compose
+
+    - name: Start Private Network
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
       run: |
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        unzip awscliv2.zip
-        sudo ./aws/install --update 
+        cd contrib/localnet
+        docker compose build zetacore0 eth && docker compose build orchestrator
+        docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+
+    - name: Run Smoke Test
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
+      run: |
+        cd contrib/localnet
+        docker compose up orchestrator --exit-code-from orchestrator
+        if [ $? -ne 0 ]; then
+          echo "Smoke Test Failed"
+          exit 1
+        fi
+
+  upload:
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    needs: 
+      - build-and-test
+      - smoke-test
+
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: setup-git-credentials
+      uses: de-vri-es/setup-git-credentials@v2.0.8
+      with:
+        credentials: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }} 
+
+    - name: Get branch name
+      id: branch-name
+      uses: tj-actions/branch-names@v6
+
+    - name: Git Hash
+      run: |
+        echo "GIT_HASH=$(git rev-parse --short HEAD)" >> ${GITHUB_ENV}
+        echo "WORKSPACE_DIR=$(pwd)" >> ${GITHUB_ENV}
+        ls -lah ./
+
+    - name: set-branch-name
+      uses: ./.github/actions/set-branch-name
+      with:
+        github_ref: "${{github.ref}}"
+        github_event: "${{ github.event_name }}"
+        github_head_ref: "${{ github.event.pull_request.head.ref }}"
+        github_commit_sha: "${{ env.GIT_HASH }}"
+        current_branch_name: "${{ steps.branch-name.outputs.current_branch }}"
+
+    - uses: actions/cache@v3
+      with:
+        path: |
+          ~/.cache/go-build
+          ~/go/pkg/mod
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: |
+          ${{ runner.os }}-go-
+
+    - name: build-zetavisor
+      uses: ./.github/actions/build-zetavisor
+      with:
+        zetavisor_version: "zetavisor-v0.1.3"
+        workspace_dir: "${{ env.WORKSPACE_DIR }}"
+
+    - name: install awscli
+      uses: ./.github/actions/install-awscli
+      with:
+        download_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
+
+    - uses: actions/download-artifact@v3
+      with:
+        name: binaries-${{ github.sha }}
+        path: ./
 
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
@@ -85,6 +155,11 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
         aws-region: ${{ env.AWS_REGION }}
+
+    - name: Debug step
+      run: |
+        pwd
+        ls -lah ./
 
     - name: upload-files-to-s3
       uses: ./.github/actions/upload-to-s3
@@ -96,15 +171,16 @@ jobs:
           zetacored
           zetaclientd
 
-    ## Not being used 
-    # - name: Build, tag, and push image to Amazon ECR
-    #   uses:  ./.github/actions/upload-to-ecr
-    #   with:
-    #     DOCKER_FILENAME: Dockerfile.zetacore_binary
-    #     ECR_REPOSITORY: zetachain
-    #     IMAGE_TAG: latest
+    - name: Build, tag, and push docker images
+      uses:  ./.github/actions/build-docker-images
+      with:
+        DOCKER_FILENAME: Dockerfile
+        REPOSITORY_NAME: zeta-node
+        IMAGE_TAG: ${{ env.TAG_NAME }}
+        GHCR_USERNAME: ${{ secrets.PAT_GITHUB_SERVICE_ACCT_USERNAME }}
+        GHCR_TOKEN: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
 
-    ## Approval will be required closer to mainnet
+    # # Approval will be required closer to mainnet
     # - name: Require Approval To Create a Release
     #   uses: softprops/action-gh-release@v1
     #   if: startsWith(github.ref, 'refs/tags/athens')
@@ -122,3 +198,20 @@ jobs:
         files: |
           zetacored
           zetaclientd
+
+  upgrade_path_testing:
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+    needs:
+      - upload
+
+    steps:
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+
+    - name: upgrade-path-testing
+      if: startsWith(github.ref, 'refs/tags/')
+      uses: ./.github/actions/upgrade-testing
+      with:
+        github_token: ${{ secrets.PAT_GITHUB_SERVICE_ACCT }}
diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,18 +2,21 @@ name: Deploy ZetaChain Update
 on:
   workflow_dispatch:
     inputs:
-      UPGRADE_NAME:
-        description: 'Name of the upgrade (0.0.1) - In most cases it will match the tag name'
-        type: string
-        required: true
-      UPGRADE_BLOCK_HEIGHT:
-        description: 'What block height to stop and upgrade'
-        type: string
-        required: false
       ENVIRONMENT:
-        description: 'What Environment to deploy into (athens2, development)'
+        description: 'What Environment to deploy into (athens2, development)?'
         type: environment
         required: true
+      UPGRADE_BLOCK_HEIGHT:
+        description: 'What block height to stop and upgrade? (Cosmovisor Only)'
+        type: string
+        required: false
+      DEPLOYMENT_METHOD:
+        description: 'Do you want to use Cosmovisor or the more dangerous binary replacement method?'
+        type: choice
+        required: true
+        options: 
+          - cosmovisor
+          - binary_replacement
 
 env:
   S3_BUCKET_NAME: "zetachain-deployment-files"
@@ -48,15 +51,6 @@ jobs:
             echo "CHAIN_ID=athens_7001-1" >> $GITHUB_ENV
           fi
 
-      - name: Get Checksum
-        run: |
-          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetacored ./ || exit 1
-          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetaclientd ./ || exit 1
-          ZETACORED_CHECKSUM=$(shasum -b -a 256 zetacored | cut -d ' ' -f 1)
-          ZETACLIENTD_CHECKSUM=$(shasum -b -a 256 zetaclientd | cut -d ' ' -f 1)
-          echo "ZETACORED_CHECKSUM=$ZETACORED_CHECKSUM" >> $GITHUB_ENV
-          echo "ZETACLIENTD_CHECKSUM=$ZETACLIENTD_CHECKSUM" >> $GITHUB_ENV
-
       # Approval needed to deploy to environments other than development
       # - uses: trstringer/manual-approval@v1
       #   if : ${{ github.event.inputs.ENVIRONMENT != 'development' }}
@@ -76,17 +70,54 @@ jobs:
           echo  ${{ github.event.inputs.UPGRADE_BLOCK_HEIGHT }}
           echo  ${{ env.ZETACORED_CHECKSUM }}
           echo  ${{ env.ZETACLIENTD_CHECKSUM }}
-
-      - name: Cosmovisor Upgrade Proposal and Vote
-        uses:  ./.github/actions/cosmovisor-upgrade
+          echo  ${{ github.event.inputs.DEPLOYMENT_METHOD }}
+      - name: Update Nodes via Binary Replacement (Dangerous Method) 
+        uses:  ./.github/actions/deploy-binaries
+        if:  ${{ github.event.inputs.DEPLOYMENT_METHOD == 'binary_replacement' }}
         with:
-          UPGRADE_NAME: ${{ github.event.inputs.UPGRADE_NAME }}
+          S3_BUCKET_NAME: ${{ env.S3_BUCKET_NAME }}
+          TAKE_SNAPSHOTS: true
+          BRANCH_OR_TAG_NAME: ${{ github.ref_name }}
+
+    ## Cosmovisor Actions Start Here
+      - name: Block Dangerous Updates To Public Networks
+        if: ${{ github.event.inputs.DEPLOYMENT_METHOD == 'binary_replacement' && github.event.inputs.ENVIRONMENT  != 'development' }}
+        run: |
+          echo  "ERROR: CANNOT USE DANGEROUS DEPLOYMENT METHODS FOR ATHENS AND OTHER PUBLIC NETWORKS"
+          exit 1
+
+      - name: Check Upgrade Handler Name Matches Tag
+        if:  ${{ github.event.inputs.DEPLOYMENT_METHOD == 'cosmovisor' }}
+        run: |
+          UPGRADE_HANDLER_NAME=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"')
+          echo $UPGRADE_HANDLER_NAME
+          if [ ${{ github.ref_name }} != $UPGRADE_HANDLER_NAME ]; then
+            echo "ERROR: The name of this release does not match the releaseVersion const in app/setup_handlers.go"
+            echo "Did you forget to update the 'releaseVersion' const in app/setup_handlers.go?" 
+            exit 1
+          fi
+          echo "releaseVersion' const in app/setup_handlers.go matches this tagged release - Moving Forward!"
+    
+      - name: Get Checksum
+        if: ${{ github.event.inputs.DEPLOYMENT_METHOD == 'cosmovisor' }}
+        run: |
+          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetacored ./ || exit 1
+          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/${{ github.ref_name }}/zetaclientd ./ || exit 1
+          ZETACORED_CHECKSUM=$(shasum -b -a 256 zetacored | cut -d ' ' -f 1)
+          ZETACLIENTD_CHECKSUM=$(shasum -b -a 256 zetaclientd | cut -d ' ' -f 1)
+          echo "ZETACORED_CHECKSUM=$ZETACORED_CHECKSUM" >> $GITHUB_ENV
+          echo "ZETACLIENTD_CHECKSUM=$ZETACLIENTD_CHECKSUM" >> $GITHUB_ENV
+
+      - name: Update Nodes via Cosmovisor Upgrade Proposal
+        uses:  ./.github/actions/cosmovisor-upgrade
+        if: ${{ github.event.inputs.DEPLOYMENT_METHOD == 'cosmovisor' }}
+        with:
+          UPGRADE_NAME: ${{ github.ref_name }}
           CHAIN_ID: ${{ env.CHAIN_ID }}
-          DESCRIPTION: "Description Goes Here"
+          DESCRIPTION: ${{ github.event.inputs.UPGRADE_NAME }}
           ZETACORED_CHECKSUM: ${{ env.ZETACORED_CHECKSUM }}
           ZETACORED_URL: "https://${{ env.S3_BUCKET_NAME }}.s3.amazonaws.com/${{ github.ref_name }}/zetacored"
           ZETACLIENTD_CHECKSUM: ${{ env.ZETACLIENTD_CHECKSUM }}
           ZETACLIENTD_URL: "https://${{ env.S3_BUCKET_NAME }}.s3.amazonaws.com/${{ github.ref_name }}/zetaclientd"
           API_ENDPOINT: "https://api.${{ github.event.inputs.ENVIRONMENT }}.zetachain.com"
           UPGRADE_BLOCK_HEIGHT: ${{ github.event.inputs.UPGRADE_BLOCK_HEIGHT }}
-
