making the upgrade-path testing library also install go and make the zetacore binary for the script to utilize.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,11 +50,11 @@ jobs:
         make install
         cp "$HOME"/go/bin/* ./
 
-#    - name: Test
-#      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-#      run: |
-#        echo "Running Build Tests"
-#        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
+    - name: Test
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
+      run: |
+        echo "Running Build Tests"
+        go test -v -coverprofile coverage.out  $(go list ./... | grep -v /x/zetacore/)
 
     - name: Save Binaries as Artifacts
       uses: actions/upload-artifact@v3
@@ -64,38 +64,38 @@ jobs:
             zetacored
             zetaclientd
         
-#  smoke-test:
-#    runs-on: ubuntu-latest
-#    timeout-minutes: 30
-#    steps:
-#    - uses: actions/checkout@v3
-#
-#    - name: install-docker-compose
-#      uses: ./.github/actions/install-docker-compose
-#
-#    - name: Start Private Network
-#      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-#      run: |
-#        cd contrib/localnet
-#        docker compose build zetacore0 eth && docker compose build orchestrator
-#        docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
-#
-#    - name: Run Smoke Test
-#      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
-#      run: |
-#        cd contrib/localnet
-#        docker compose up orchestrator --exit-code-from orchestrator
-#        if [ $? -ne 0 ]; then
-#          echo "Smoke Test Failed"
-#          exit 1
-#        fi
+  smoke-test:
+    runs-on: ubuntu-latest
+    timeout-minutes: 30
+    steps:
+    - uses: actions/checkout@v3
+
+    - name: install-docker-compose
+      uses: ./.github/actions/install-docker-compose
+
+    - name: Start Private Network
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
+      run: |
+        cd contrib/localnet
+        docker compose build zetacore0 eth && docker compose build orchestrator
+        docker compose up -d zetacore0 zetacore1 zetaclient0 zetaclient1 eth bitcoin
+
+    - name: Run Smoke Test
+      if: ${{ env.GITHUB_REF_NAME != 'athens2-develop' }}
+      run: |
+        cd contrib/localnet
+        docker compose up orchestrator --exit-code-from orchestrator
+        if [ $? -ne 0 ]; then
+          echo "Smoke Test Failed"
+          exit 1
+        fi
 
   upload:
     runs-on: ubuntu-latest
     timeout-minutes: 15
     needs: 
       - build-and-test
-      #- smoke-test
+      - smoke-test
 
     steps:
     - uses: actions/checkout@v3
