Moved handler to upgrade_path_testing job

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -294,20 +294,6 @@ jobs:
           github_commit_sha: "${{ env.GIT_HASH }}"
           current_branch_name: "${{ steps.branch-name.outputs.current_branch }}"
 
-      - name: Major Version in Upgrade Handler Must Match Tag
-        if: ( startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release') ) && !endsWith(github.ref, '-rc')
-        run: |
-          UPGRADE_HANDLER_MAJOR_VERSION=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"' | cut -d '.' -f1)
-          echo $UPGRADE_HANDLER_MAJOR_VERSION
-          GITHUB_TAG_MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d '.' -f1)
-          if [ $GITHUB_TAG_MAJOR_VERSION != $UPGRADE_HANDLER_MAJOR_VERSION ]; then
-            echo "ERROR: The major version of this release (${{ github.ref_name }}) does not match the major version in the releaseVersion constant ($UPGRADE_HANDLER_MAJOR_VERSION) found in app/setup_handlers.go"
-            echo "Did you forget to update the 'releaseVersion' in app/setup_handlers.go?" 
-            exit 1
-          fi
-
-          echo "The major version found in 'releaseVersion' in app/setup_handlers.go matches this tagged release - Moving Forward!"
-
       - uses: actions/download-artifact@v3
         with:
           name: binaries-${{ github.sha }}
@@ -387,6 +373,19 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+
+      - name: Major Version in Upgrade Handler Must Match Tag
+        if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release') 
+        run: |
+          UPGRADE_HANDLER_MAJOR_VERSION=$(cat app/setup_handlers.go | grep "const releaseVersion" | cut -d ' ' -f4 | tr -d '"' | cut -d '.' -f1)
+          echo $UPGRADE_HANDLER_MAJOR_VERSION
+          GITHUB_TAG_MAJOR_VERSION=$(echo ${{ github.ref_name }} | cut -d '.' -f1)
+          if [ $GITHUB_TAG_MAJOR_VERSION != $UPGRADE_HANDLER_MAJOR_VERSION ]; then
+            echo "ERROR: The major version of this release (${{ github.ref_name }}) does not match the major version in the releaseVersion constant ($UPGRADE_HANDLER_MAJOR_VERSION) found in app/setup_handlers.go"
+            echo "Did you forget to update the 'releaseVersion' in app/setup_handlers.go?" 
+            exit 1
+          fi
+          echo "The major version found in 'releaseVersion' in app/setup_handlers.go matches this tagged release - Moving Forward!"
 
       - name: upgrade-path-testing
         uses: ./.github/actions/upgrade-testing
