Testing Environment selection

diff --git a/.github/workflows/deploy-aws.yml b/.github/workflows/deploy-aws.yml
--- a/.github/workflows/deploy-aws.yml
+++ b/.github/workflows/deploy-aws.yml
@@ -1,92 +1,158 @@
-name: Build & Deploy To EC2 (aws/staging)
+name: Deploy To AWS
+
+## TODO 
+  # Remove static IAM creds and use short lived via Role Assumption
+    # Simplifies the environment name/ set AWS credentials section
+    # Replace S3 Buckets with ones dedicated for GitHub Actions and don't expose the account ID 
+  # Add Testing Stage
+  # Add Rollback Stage
+  # Potentially setup staging env to spun up JIT
 
 on:
   push:
     branches:
       - develop
+      - charliemc/zeta-709-update-cicd-pipeline
     tags:
       - athens-v*
 env:
-  S3_BUCKET: s3://source-files-821351686724/deployment-files
-  # AWS_REGION: us-east-1
+  AWS_REGION: us-east-1
 
 jobs:
-  # set-env-vars: TODO - Set Env Vars based on environment or branch
-  #     runs-on: ubuntu-latest
-  #     steps:
-  #       - uses: actions/checkout@v3
 
-  build-aws:
+  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
 
-      # - name: Set up Go
-      #   uses: actions/setup-go@v3
-      #   with:
-      #     go-version: 1.17
+      - name: Set Environment Variables"
+        run: |
+          GITHUB_REF_NAME=${{ github.ref_name }}  
+          echo $GITHUB_REF_NAME
+          
+          if [[ $GITHUB_REF_NAME == "charliemc/zeta-709-update-cicd-pipeline" ]]; then 
+            export ENVIRONMENT_NAME=STAGING
+            export S3_BUCKET=s3://source-files-821351686724/deployment-files
+          elif [[ ${GITHUB_REF_NAME:0:8} == "athens-v" ]]; then 
+            echo "Using Athens Environment"
+            export ENVIRONMENT_NAME=ATHENS  
+            export S3_BUCKET=s3://source-files-070014318019/deployment-files
+          else 
+            echo "ERROR: Unknown value for "github.ref_name" $GITHUB_REF_NAME"
+            echo "Exiting"
+            exit 1   
+          fi
 
-      # - name: Build
-      #   run: make install
+          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
+          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
+          echo "Environment Name:$ENVIRONMENT_NAME"
 
-      # ## - name: Test
-      # ##   run: go test -v -coverprofile coverage.out  ./...
-
-      # - name: Create Package
-      #   run: |
-      #     export PACKAGE_TIMESTAMP=$(date +"%s")
-      #     echo "::set-env name=PACKAGE_TIMESTAMP::$PACKAGE_TIMESTAMP"
-      #     mkdir deployment-${PACKAGE_TIMESTAMP}
-      #     mv $HOME/go/bin/zetacored deployment-${PACKAGE_TIMESTAMP}
-      #     mv $HOME/go/bin/zetaclientd deployment-${PACKAGE_TIMESTAMP}
-      #     mv build/zetaclient-start.sh deployment-${PACKAGE_TIMESTAMP}
-      #     mv build/zetacored-start.sh deployment-${PACKAGE_TIMESTAMP}
-      #     tar -czvf deployment-${PACKAGE_TIMESTAMP}.tar.gz deployment-${PACKAGE_TIMESTAMP}/*
-
-      # - name: Install AWS CLI
-      #   run: |
-      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-      #     unzip awscliv2.zip
-      #     sudo ./aws/install
-
-      # - name: Configure AWS credentials
-      #   uses: aws-actions/configure-aws-credentials@v1
-      #   with:
-      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SPARTA }}
-      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPARTA }}
-      #     aws-region: us-east-1
-
-      # - name: s3
-      #   run: |
-      #     echo $PACKAGE_TIMESTAMP
-      #     aws s3 cp deployment-${PACKAGE_TIMESTAMP}.tar.gz $S3_BUCKET/deployment-${PACKAGE_TIMESTAMP}.tar.gz
-
-      # - name: Update SSM Parameter - /deployments/latest-deployment-id
-      #   run: aws ssm put-parameter --overwrite --name '/deployments/latest-deployment-id' --value deployment-${PACKAGE_TIMESTAMP}  > /dev/null 2>&1
-
-  deploy:
-    needs: build-aws
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+      - name: Set Up Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.17
 
       - name: Install AWS CLI
         run: |
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
           unzip awscliv2.zip
-          sudo ./aws/install
+          sudo ./aws/install --update 
 
-      - name: Configure AWS credentials
+      - name: Configure AWS Credentials - Staging
+        if: ${{ env.ENVIRONMENT_NAME == 'STAGING' }}
         uses: aws-actions/configure-aws-credentials@v1
         with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SPARTA }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPARTA }}
-          aws-region: us-east-1
+          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID_SPARTA }}          
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPARTA }}          
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Configure AWS Credentials - Athens
+        if: ${{ env.ENVIRONMENT_NAME == 'ATHENS' }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID_ATHENS }}          
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ATHENS }}          
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Build Binaries
+        run: make install
+
+      # - name: Test
+      #   run: go test -v -coverprofile coverage.out  ./...
+
+      - name: Create Package
+        run: |
+          export PACKAGE_TIMESTAMP=$(date +"%s")
+          echo "PACKAGE_TIMESTAMP=$PACKAGE_TIMESTAMP" >> $GITHUB_ENV
+          mkdir deployment-${PACKAGE_TIMESTAMP}
+          mv $HOME/go/bin/zetacored deployment-${PACKAGE_TIMESTAMP}
+          mv $HOME/go/bin/zetaclientd deployment-${PACKAGE_TIMESTAMP}
+          mv build/zetaclient-start.sh deployment-${PACKAGE_TIMESTAMP}
+          mv build/zetacored-start.sh deployment-${PACKAGE_TIMESTAMP}
+          tar -czvf deployment-${PACKAGE_TIMESTAMP}.tar.gz deployment-${PACKAGE_TIMESTAMP}/*
+
+      - name: Push Package To S3
+        run: |
+          echo $PACKAGE_TIMESTAMP
+          aws s3 cp deployment-${PACKAGE_TIMESTAMP}.tar.gz ${{ env.S3_BUCKET }}/deployment-${PACKAGE_TIMESTAMP}.tar.gz
+
+      - name: Update Latest Deployment ID SSM Parameter
+        run: aws ssm put-parameter --overwrite --name '/deployments/latest-deployment-id' --value deployment-${PACKAGE_TIMESTAMP}  > /dev/null 2>&1
+
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set Environment Variables"
+        run: |
+          GITHUB_REF_NAME=${{ github.ref_name }}  
+          echo $GITHUB_REF_NAME
+          
+          if [[ $GITHUB_REF_NAME == "charliemc/zeta-709-update-cicd-pipeline" ]]; then 
+            export ENVIRONMENT_NAME=STAGING
+            export S3_BUCKET=s3://source-files-821351686724/deployment-files
+          elif [[ ${GITHUB_REF_NAME:0:8} == "athens-v" ]]; then 
+            echo "Using Athens Environment"
+            export ENVIRONMENT_NAME=ATHENS  
+            export S3_BUCKET=s3://source-files-070014318019/deployment-files
+          else 
+            echo "ERROR: Unknown value for "github.ref_name" $GITHUB_REF_NAME"
+            echo "Exiting"
+            exit 1   
+          fi
+
+          echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV
+          echo "ENVIRONMENT_NAME=$ENVIRONMENT_NAME" >> $GITHUB_ENV
+          echo "Environment Name:$ENVIRONMENT_NAME"
+
+      - name: Install AWS CLI
+        run: |
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install --update 
+
+      - name: Configure AWS Staging credentials
+        if: ${{ env.ENVIRONMENT_NAME == 'STAGING' }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID_SPARTA }}          
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPARTA }}          
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Configure AWS Athens credentials
+        if: ${{ env.ENVIRONMENT_NAME == 'ATHENS' }}
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id:  ${{ secrets.AWS_ACCESS_KEY_ID_ATHENS }}          
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ATHENS }}          
+          aws-region: ${{ env.AWS_REGION }}
 
       - name: Get Deployment ID
         run: |
           export DEPLOYMENT_ID=$(aws ssm get-parameter --name '/deployments/latest-deployment-id' | jq .Parameter.Value -r)
-          echo "::set-env name=DEPLOYMENT_ID::$DEPLOYMENT_ID"
+          echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
 
       - name: Snapshot Instances
         run: |
@@ -103,7 +169,7 @@ jobs:
       - name: Copy Package Files
         run: |
           source build/bash_functions
-          COMMAND_ID=$(run_ssm_commands "aws s3 cp $S3_BUCKET/$DEPLOYMENT_ID.tar.gz /tmp, tar -xzvf /tmp/$DEPLOYMENT_ID.tar.gz -C /deployment-files")
+          COMMAND_ID=$(run_ssm_commands "aws s3 cp ${{ env.S3_BUCKET }}/$DEPLOYMENT_ID.tar.gz /tmp, tar -xzvf /tmp/$DEPLOYMENT_ID.tar.gz -C /deployment-files")
           check_cmd_status $COMMAND_ID
 
       - name: Stop ZetaChain
@@ -128,44 +194,3 @@ jobs:
           COMMAND_ID=$(run_ssm_commands "systemctl restart zetaclientd, systemctl restart zetacored")
           check_cmd_status $COMMAND_ID
 
-## TODO 
-  # Testing
-  # Rollback 
-
-  # test:
-  #   needs: deploy
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-
-  #     - name: Install AWS CLI 
-  #       run: |
-  #         curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-  #         unzip awscliv2.zip
-  #         sudo ./aws/install
-
-  #     - name: Configure AWS credentials
-  #       uses: aws-actions/configure-aws-credentials@v1
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SPARTA }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SPARTA }}
-  #         aws-region: us-east-1
-
-  #     - name: Get Deployment ID
-  #       run: |
-  #         export DEPLOYMENT_ID=$(aws ssm get-parameter --name '/deployments/latest-deployment-id' | jq .Parameter.Value -r)
-  #         echo "::set-env name=DEPLOYMENT_ID::$DEPLOYMENT_ID"
-
-  #     # TODO - Put Tests Here
-
-  #     - name: Update Last Successful Deployment ID - /deployments/latest-successful-deployment-id
-  #       run: |
-  #         aws ssm put-parameter --overwrite --name '/deployments/latest-successful-deployment-id' --value $DEPLOYMENT_ID > /dev/null 2>&1
-
-  # rollback: # Setup RollBack actions in case of failure
-  #   needs: deploy
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v2
-
-  
