adding while loop

diff --git a/.github/workflows/execute_advanced_tests.yaml b/.github/workflows/execute_advanced_tests.yaml
--- a/.github/workflows/execute_advanced_tests.yaml
+++ b/.github/workflows/execute_advanced_tests.yaml
@@ -45,9 +45,9 @@ jobs:
           echo "Monitoring Orchestrator container with ID: $container_id"
           while true; do
               echo "get current status"
-              current_status=$(docker ps -q | grep $container_id)
+              current_status=$(docker ps -q | grep $container_id || echo "docker-ps-error")
               echo "current status: ${current_status}"
-              if [ -z "$current_status" ]; then
+              if [ "$current_status" == "docker-ps-error" ]; then
                   echo "no current container get logs"
                   docker logs $container_id || echo "no logs"
                   echo "-----------------------------------"
@@ -83,9 +83,9 @@ jobs:
           echo "Monitoring Orchestrator container with ID: $container_id"
           while true; do
               echo "get current status"
-              current_status=$(docker ps -q | grep $container_id)
+              current_status=$(docker ps -q | grep $container_id || echo "docker-ps-error")
               echo "current status: ${current_status}"
-              if [ -z "$current_status" ]; then
+              if [ "$current_status" == "docker-ps-error" ]; then
                   echo "no current container get logs"
                   docker logs $container_id || echo "no logs"
                   echo "-----------------------------------"
@@ -121,9 +121,9 @@ jobs:
           echo "Monitoring Orchestrator container with ID: $container_id"
           while true; do
               echo "get current status"
-              current_status=$(docker ps -q | grep $container_id)
+              current_status=$(docker ps -q | grep $container_id || echo "docker-ps-error")
               echo "current status: ${current_status}"
-              if [ -z "$current_status" ]; then
+              if [ "$current_status" == "docker-ps-error" ]; then
                   echo "no current container get logs"
                   docker logs $container_id || echo "no logs"
                   echo "-----------------------------------"
@@ -159,9 +159,9 @@ jobs:
           echo "Monitoring Orchestrator container with ID: $container_id"
           while true; do
               echo "get current status"
-              current_status=$(docker ps -q | grep $container_id)
+              current_status=$(docker ps -q | grep $container_id || echo "docker-ps-error")
               echo "current status: ${current_status}"
-              if [ -z "$current_status" ]; then
+              if [ "$current_status" == "docker-ps-error" ]; then
                   echo "no current container get logs"
                   docker logs $container_id || echo "no logs"
                   echo "-----------------------------------"
