refactor: error message

diff --git a/.github/workflows/generate-go.yml b/.github/workflows/generate-go.yml
--- a/.github/workflows/generate-go.yml
+++ b/.github/workflows/generate-go.yml
@@ -22,4 +22,9 @@ jobs:
 
       - name: Check for changes
         run: |
-          git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol -- x
+          if git diff --exit-code --ignore-space-change --ignore-all-space --ignore-cr-at-eol -- x; then
+            echo "Generated Go files are up-to-date."
+          else
+            echo "::error::Generated Go files are not up-to-date, please run 'make proto' locally and commit changes."
+            exit 1
+          fi
