fix: fix the cleanup step in the rc-release and publish-release pipelines

diff --git a/.github/workflows/publish-release.yml b/.github/workflows/publish-release.yml
--- a/.github/workflows/publish-release.yml
+++ b/.github/workflows/publish-release.yml
@@ -133,4 +133,4 @@ jobs:
       - name: Clean Up Workspace
         if: always()
         shell: bash
-        run: rm -rf *
+        run: sudo rm -rf * || echo "failed to cleanup workspace please investigate"
diff --git a/.github/workflows/rc-release.yml b/.github/workflows/rc-release.yml
--- a/.github/workflows/rc-release.yml
+++ b/.github/workflows/rc-release.yml
@@ -85,4 +85,4 @@ jobs:
       - name: Clean Up Workspace
         if: always()
         shell: bash
-        run: rm -rf *
+        run: sudp rm -rf * || echo "failed to clean workspace please investigate"
