Update rc-release.yml
Co-authored-by: Lucas Bertrand <lucas.bertrand.22@gmail.com>

diff --git a/.github/workflows/rc-release.yml b/.github/workflows/rc-release.yml
--- a/.github/workflows/rc-release.yml
+++ b/.github/workflows/rc-release.yml
@@ -85,4 +85,4 @@ jobs:
       - name: Clean Up Workspace
         if: always()
         shell: bash
-        run: sudp rm -rf * || echo "failed to clean workspace please investigate"
+        run: sudo rm -rf * || echo "failed to clean workspace please investigate"
