update binary names

diff --git a/.github/workflows/upgrade_path_testing.yaml b/.github/workflows/upgrade_path_testing.yaml
--- a/.github/workflows/upgrade_path_testing.yaml
+++ b/.github/workflows/upgrade_path_testing.yaml
@@ -89,16 +89,17 @@ jobs:
         working-directory: "zetavisor/cosmovisor"
         run: |
           echo "*********INSTALL ZETAVISOR*********"
-          go get github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/zetavisor
-          go install github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/zetavisor
-          zetavisor version || echo "zetavisor failed to install."
-          
           echo "*********SETUP ZETAVISOR DIRECTORIES*********"
           rm -rf /home/runner/.zetacored
           mkdir -p /home/runner/.zetacored/zetavisor
           mkdir -p /home/runner/.zetacored/zetavisor/genesis/bin
           mkdir -p /home/runner/.zetacored/zetavisor/upgrades/${{ github.event.inputs.version }}/bin
           mkdir -p /home/runner/.zetacored/zetavisor/upgrades/${{ github.event.inputs.upgrade_name }}/bin
+
+          go get github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/zetavisor
+          go install github.com/zeta-chain/cosmos-sdk/cosmovisor/cmd/zetavisor
+          zetavisor version || echo "zetavisor failed to install."
+          
 
       - name: "DOWNLOAD_STATE_EXPORT_AND_BINARIES"
         run: |
@@ -229,6 +230,7 @@ jobs:
           minor_version = version.split(".")[1]
           sub_version = version.split(".")[2]
           
+          print("${{ github.event.inputs.version }}")
           git_env_file = open(os.environ["GITHUB_ENV"], "a+")
           if major_version == first_major_version and minor_version != first_minor_version:
               git_env_file.write("UPGRADE_TYPE=NONCON")
